-- K-STREAM Supabase setup
-- Run once in Supabase SQL Editor.
-- Existing rows in public.drakor are preserved.

create table if not exists public.drakor (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  title text not null,
  image text,
  genre text,
  year text,
  synopsis text,
  episodes jsonb not null default '[]'::jsonb
);

create table if not exists public.drakor_ratings (
  id bigint generated by default as identity primary key,
  drakor_id bigint not null references public.drakor(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (drakor_id, user_id)
);

create table if not exists public.drakor_comments (
  id bigint generated by default as identity primary key,
  drakor_id bigint not null references public.drakor(id) on delete cascade,
  episode_index integer,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name text not null check (char_length(name) between 1 and 60),
  comment text not null check (char_length(comment) between 1 and 1200),
  status text not null default 'published' check (status in ('published', 'pending', 'hidden')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists drakor_ratings_drakor_idx on public.drakor_ratings (drakor_id);
create index if not exists drakor_comments_lookup_idx on public.drakor_comments (drakor_id, created_at desc);

create or replace view public.drakor_rating_summary
with (security_invoker = true) as
select
  drakor_id,
  round(avg(rating)::numeric, 1) as average_rating,
  count(*)::bigint as rating_count
from public.drakor_ratings
group by drakor_id;

alter table public.drakor enable row level security;
alter table public.drakor_ratings enable row level security;
alter table public.drakor_comments enable row level security;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('drakor', 'drakor_ratings', 'drakor_comments')
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      existing_policy.policyname,
      existing_policy.schemaname,
      existing_policy.tablename
    );
  end loop;
end
$$;

drop policy if exists "Public can read drakor" on public.drakor;
create policy "Public can read drakor"
  on public.drakor for select
  using (true);

drop policy if exists "Authenticated users can insert drakor" on public.drakor;
create policy "Authenticated users can insert drakor"
  on public.drakor for insert
  to authenticated
  with check (auth.uid() is not null);

drop policy if exists "Authenticated users can update drakor" on public.drakor;
create policy "Authenticated users can update drakor"
  on public.drakor for update
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

drop policy if exists "Authenticated users can delete drakor" on public.drakor;
create policy "Authenticated users can delete drakor"
  on public.drakor for delete
  to authenticated
  using (auth.uid() is not null);

drop policy if exists "Public can read ratings" on public.drakor_ratings;
create policy "Public can read ratings"
  on public.drakor_ratings for select
  using (true);

drop policy if exists "Users can insert own ratings" on public.drakor_ratings;
create policy "Users can insert own ratings"
  on public.drakor_ratings for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own ratings" on public.drakor_ratings;
create policy "Users can update own ratings"
  on public.drakor_ratings for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Public can read published comments" on public.drakor_comments;
create policy "Public can read published comments"
  on public.drakor_comments for select
  using (status = 'published');

drop policy if exists "Users can create comments" on public.drakor_comments;
create policy "Users can create comments"
  on public.drakor_comments for insert
  to authenticated
  with check (auth.uid() = user_id and status in ('published', 'pending'));

revoke all on public.drakor from anon, authenticated;
revoke all on public.drakor_ratings from anon, authenticated;
revoke all on public.drakor_comments from anon, authenticated;

grant select on public.drakor to anon, authenticated;
grant insert, update, delete on public.drakor to authenticated;
grant select, insert, update on public.drakor_ratings to authenticated;
grant select on public.drakor_ratings to anon;
grant select, insert on public.drakor_comments to authenticated;
grant select on public.drakor_comments to anon;
grant select on public.drakor_rating_summary to anon, authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Supabase Dashboard:
-- 1. Authentication > Providers > Anonymous Sign-Ins: enable.
-- 2. The browser login admin/110301 is a demo UI gate, not production security.
-- 3. For production, replace anonymous catalog write policies with real admin roles.
-- 4. Never use the service_role key in browser code.
